Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2023-10, with the labels that each got.

#412 fix(agents-kit): do not use @static reference to images
  docs-kits/kits/knowledge-agents/adoption-view/intro.md
  docs-kits/kits/knowledge-agents/development-view/Arc42.md
  docs-kits/kits/knowledge-agents/development-view/architecture.md
  docs-kits/kits/knowledge-agents/development-view/modules.md
  docs-kits/kits/knowledge-agents/operation-view/deployment.md
  docs-kits/kits/knowledge-agents/page_changelog.md
Labels: bug

#413 fix(agents-kit): Icon links are case-sensitive.
  docs-kits/kits/knowledge-agents/adoption-view/intro.md
  docs-kits/kits/knowledge-agents/development-view/Arc42.md
  docs-kits/kits/knowledge-agents/development-view/architecture.md
  docs-kits/kits/knowledge-agents/operation-view/deployment.md
  docs-kits/kits/knowledge-agents/page_changelog.md
Labels: bug

#415 Initial Blogpost for Open Planning Days
  blog/2023-10-26-open-planning.mdx
  static/img/Eclipse-TractusX-Open-Planning-10-23.png
  utils/newsTitles.js
Labels: website

#417 Blog Post Update for Open Planning Days
  blog/2023-10-26-open-planning.mdx
Labels: website

#419 fix(trg-2-4) broken link reference to trg-5-08
  docs/release/trg-2/trg-2-4.md
Labels: bug, documentation

#443 feat(tutorials): Initial commit to provide the tutorials structure
  docs/tutorials.md
  docs/tutorials/e2e.md
  docs/tutorials/e2e/adopt/adopt.md
  docs/tutorials/e2e/adopt/edcUI.md
  docs/tutorials/e2e/adopt/knowledgeAgent.md
  docs/tutorials/e2e/adopt/walletEDC.md
  docs/tutorials/e2e/boost/boost.md
  docs/tutorials/e2e/boost/connectBackend.md
  docs/tutorials/e2e/boost/consumeData.md
  docs/tutorials/e2e/boost/initiateDataSpace.md
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/connect/.runSingleTutorials.md
  docs/tutorials/e2e/connect/connect.md
  docs/tutorials/e2e/connect/deployComponents.md
  docs/tutorials/e2e/connect/prepareInfrastructure.md
  docs/tutorials/e2e/gettingStarted/gettingStarted.md
  docs/tutorials/e2e/inform/.deepDives.md
  docs/tutorials/e2e/inform/.techAssessment.md
  docs/tutorials/e2e/inform/architecture.md
  docs/tutorials/e2e/inform/inform.md
  docs/tutorials/e2e/inform/onboardingMaterial.md
  docs/tutorials/e2e/prerequisites/prerequisites.md
  docs/tutorials/e2e/utilize/deploytoprod.md
  docs/tutorials/e2e/utilize/utilize.md
  docs/tutorials/technicalComponents.md
  docs/tutorials/technicalComponents/EDC/EDC.md
  docs/tutorials/technicalComponents/IRS/IRS.md
  docs/tutorials/technicalComponents/digitalTwinRegistry/digitalTwinRegistry.md
  docs/tutorials/technicalComponents/ssiWallet/ssiWallet.md
  docs/tutorials/useCases.md
  docs/tutorials/useCases/bpdm/bpdm.md
  docs/tutorials/useCases/sustainability/sustainability.md
  docs/tutorials/useCases/traceability/traceability.md
  docusaurus.config.js
  sidebars.js
Labels: documentation

#444 feat(tutorials): Provide initial content and structure
  docs/tutorials.md
  docs/tutorials/e2e.md
  docs/tutorials/e2e/adopt/adopt.md
  docs/tutorials/e2e/adopt/edcUI.md
  docs/tutorials/e2e/adopt/knowledgeAgent.md
  docs/tutorials/e2e/adopt/walletEDC.md
  docs/tutorials/e2e/boost/assets/components_contract_definition.png
  docs/tutorials/e2e/boost/connectBackend.md
  docs/tutorials/e2e/boost/consumeData.md
  docs/tutorials/e2e/boost/initiateDataSpace.md
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/boost/restrictData.md
  docs/tutorials/e2e/connect/.runSingleTutorials.md
  docs/tutorials/e2e/connect/assets/img.png
  docs/tutorials/e2e/connect/assets/scr_pgadmin1.png
  docs/tutorials/e2e/connect/connect.md
  docs/tutorials/e2e/connect/deployComponents.md
  docs/tutorials/e2e/connect/prepareInfrastructure.md
  docs/tutorials/e2e/gettingStarted/gettingStarted.md
  docs/tutorials/e2e/inform/.deepDives.md
  docs/tutorials/e2e/inform/.techAssessment.md
  docs/tutorials/e2e/inform/architecture.md
  docs/tutorials/e2e/inform/onboardingMaterial.md
  docs/tutorials/e2e/prerequisites/prerequisites.md
  docs/tutorials/e2e/utilize/deploytoprod.md
  docs/tutorials/e2e/utilize/utilize.md
  docs/tutorials/technicalComponents.md
  docs/tutorials/technicalComponents/EDC/EDC.md
  docs/tutorials/technicalComponents/IRS/IRS.md
  docs/tutorials/technicalComponents/digitalTwinRegistry/digitalTwinRegistry.md
  docs/tutorials/technicalComponents/ssiWallet/ssiWallet.md
  docs/tutorials/useCases.md
  docs/tutorials/useCases/bpdm/bpdm.md
  docs/tutorials/useCases/sustainability/sustainability.md
  docs/tutorials/useCases/traceability/traceability.md
  sidebars.js
Labels: documentation

#446 doc(community): Workflow from idea over feature proposal to PR
  src/pages/community.mdx
  static/img/cx_workflow_idea_to_pr.drawio.svg
Labels: documentation

#459 Adapt initial structure and content
  docs/tutorials/CHANGELOG.md
  docs/tutorials/e2e.md
  docs/tutorials/e2e/boost/boost.md
  docs/tutorials/e2e/boost/initiateDataSpace.md
  docs/tutorials/e2e/connect/connect.md
  docs/tutorials/e2e/inform/inform.md
Labels: documentation

#460 docs(connector kit): Restructure the adoption view
  docs-kits/kits/tractusx-edc/CHANGELOG.md
  docs-kits/kits/tractusx-edc/docs/kit/adoption-view/page_adoption-view.md
  docs-kits/kits/tractusx-edc/docs/kit/adoption-view/page_domain_model.md
  sidebarsDocsKits.js
Labels: documentation
