Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2023-11, with the labels that each got.

#465 doc(connector kit): Switch from transparent background to white in domain model
  static/img/domain_model.drawio.svg
Labels: documentation

#471 doc(tutorials): Keep feature branch up to date
  docs-kits/kits/Resiliency/DCM_Kit.mdx
  docs-kits/kits/Resiliency/MP_Kit.md
  docs-kits/kits/Resiliency/MaaS.md
  docs-kits/kits/Resiliency/PURIS_Kit.md
  docs-kits/kits/Resiliency/resiliency.mdx
  docs-kits/kits/tractusx-edc/CHANGELOG.md
  docs-kits/kits/tractusx-edc/docs/kit/adoption-view/page_adoption-view.md
  docs-kits/kits/tractusx-edc/docs/kit/adoption-view/page_domain_model.md
  docs-kits_versioned_docs/version-3.1.0/kits/Resiliency/DCM_Kit.mdx
  docs-kits_versioned_docs/version-3.1.0/kits/Resiliency/MP_Kit.md
  docs-kits_versioned_docs/version-3.1.0/kits/Resiliency/MaaS.md
  docs-kits_versioned_docs/version-3.1.0/kits/Resiliency/OSim_Kit.md
  docs-kits_versioned_docs/version-3.1.0/kits/Resiliency/PURIS_Kit.md
  docs-kits_versioned_docs/version-3.1.0/kits/Resiliency/resiliency.mdx
  docs-kits_versioned_sidebars/version-3.1.0-sidebars.json
  docs/tutorials/CHANGELOG.md
  docs/tutorials/e2e/boost/boost.md
  docs/tutorials/e2e/boost/consumeData.md
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/boost/restrictData.md
  docs/tutorials/e2e/connect/.runSingleTutorials.md
  docs/tutorials/e2e/connect/connect.md
  docs/tutorials/e2e/connect/deployComponents.md
  docs/tutorials/e2e/connect/prepareInfrastructure.md
  docs/tutorials/e2e/inform/.deepDives.md
  docs/tutorials/e2e/inform/.techAssessment.md
  docs/tutorials/e2e/inform/architecture.md
  docs/tutorials/e2e/inform/inform.md
  docs/tutorials/e2e/inform/onboardingMaterial.md
  docs/tutorials/e2e/prerequisites/prerequisites.md
  docusaurus.config.js
  sidebarsDocsKits.js
  static/img/domain_model.drawio.svg
  utils/previewKits.js
  utils/resiliencyItems.js
Labels: documentation

#474 doc(tutorials): adapt architecture view
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/inform/architecture.md
  static/img/architecture.drawio.svg
Labels: documentation

#461 doc(tutorials): Adaptation new structure for tutorial
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/connect/deployComponents.md
  docs/tutorials/e2e/prerequisites/prerequisites.md
Labels: documentation

#462 doc(tutorials): adapt boost part
  docs/tutorials/e2e/boost/consumeData.md
Labels: documentation

#479 docs: TRG 5.09, 5.10, 5.11 title to lose PRERELEASE postfix and other content cleanup
  docs/release/trg-5/trg-5-09.md
  docs/release/trg-5/trg-5-10.md
  docs/release/trg-5/trg-5-11.md
Labels: documentation, website

#498 doc(tutorials): adjustments of chapter 1 get an Overview after review
  docs/tutorials/e2e/inform/onboardingMaterial.md
Labels: documentation

#497 doc(tutorials): adjustments of chapter 3 consume data after review
  docs/tutorials/e2e/boost/consumeData.md
Labels: documentation

#490 doc(tutorials): adjustments after review
  docs/tutorials/e2e/prerequisites/prerequisites.md
Labels: documentation

#503 doc(tutorials): Adjustments of chapter 3 provide data after review
  docs/tutorials/e2e/boost/provideData.md
Labels: documentation

#504 doc(tutorials): Adjustments of chapter 3/Restricting users after review
  docs/tutorials/e2e/boost/restrictData.md
Labels: documentation

#505 doc(tutorials): Minor adjustments on chapter3/Consume Data
  docs/tutorials/e2e/boost/consumeData.md
Labels: documentation

#414 doc: TRG 4.07: Read-Only Filesystem (DRAFT)
  docs/release/trg-0/trg-4-07.md
Labels: documentation

#500 docs(agents): Simplify Adoption and Extend Deployment Tutorial
  docs-kits/kits/knowledge-agents/adoption-view/intro.md
  docs-kits/kits/knowledge-agents/operation-view/deployment.md
  docs-kits/kits/knowledge-agents/page_changelog.md
Labels: enhancement

#472 doc(tutorials): publish the e2e adopter journey tutorial
  blog/2023-11-22-release_tutorials.mdx
  docs/tutorials.md
  docs/tutorials/e2e/CHANGELOG.md
  docs/tutorials/e2e/boost/assets/components_contract_definition.png
  docs/tutorials/e2e/boost/boost.md
  docs/tutorials/e2e/boost/consumeData.md
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/boost/restrictData.md
  docs/tutorials/e2e/connect/assets/img.png
  docs/tutorials/e2e/connect/assets/scr_pgadmin1.png
  docs/tutorials/e2e/connect/connect.md
  docs/tutorials/e2e/connect/deployComponents.md
  docs/tutorials/e2e/connect/prepareInfrastructure.md
  docs/tutorials/e2e/e2e.md
  docs/tutorials/e2e/inform/architecture.md
  docs/tutorials/e2e/inform/inform.md
  docs/tutorials/e2e/inform/onboardingMaterial.md
  docs/tutorials/e2e/prerequisites/prerequisites.md
  docusaurus.config.js
  sidebars.js
  static/img/TractusX-Tutorials_E2E.png
  static/img/architecture.drawio
  static/img/architecture.drawio.svg
  static/img/five_steps_to_gain_value.drawio.svg
  utils/newsTitles.js
Labels: documentation, enhancement

#513 doc(tutorials): publish new tutorial section
  blog/2023-11-22-release_tutorials.mdx
Labels: documentation

#509 docs(agents-kit): extend version numbers. clarifiy standard versions.
  docs-kits/kits/knowledge-agents/adoption-view/intro.md
  docs-kits/kits/knowledge-agents/operation-view/agent_edc.md
  docs-kits/kits/knowledge-agents/operation-view/deployment.md
  docs-kits/kits/knowledge-agents/operation-view/provider.md
  docs-kits/kits/knowledge-agents/operation-view/testbed.md
  docs-kits/kits/knowledge-agents/page_changelog.md
  openApi/agents/agent-openapi.yaml
Labels: enhancement
