Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2023-09, with the labels that each got.

#375 feat: Add ECO-Pass KIT
  docs-kits/kits/Eco_Pass_KIT/changelog.md
  docs-kits/kits/Eco_Pass_KIT/page-adoption-view.md
  docs-kits/kits/Eco_Pass_KIT/page-software-development-view.md
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BatteryPass_a_example.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BatteryPass_a_example.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BusinessValue.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BusinessValue.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/development-view/adoption-view-EcoPassKIT_IT_Arch.png
  docs-kits/kits/Eco_Pass_KIT/resources/development-view/adoption-view-EcoPassKIT_IT_Arch.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/development-view/developmentview-sequence-diagramm.svg
  docs-kits/kits/Eco_Pass_KIT/resources/development-view/developmentview-sequence-diagramm.svg.license
  sidebarsDocsKits.js
Labels: enhancement

#397 docs(how to contribute): adapted wrong link syntax
  docs/oss/how-to-contribute.md
Labels: bug, documentation

#390 docs(general): activate mermaid functionality in markdown
  docusaurus.config.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#404 Releaseinformation adapted
  src/pages/release-information.md
Labels: documentation, enhancement
