Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2024-02, with the labels that each got.

#632 fix(tutorials): Update prerequisites.md - minor changes
  docs/tutorials/e2e/prerequisites/prerequisites.md
Labels: bug, documentation

#649 doc(tutorials): Update prerequisites - make it more readable
  docs/tutorials/e2e/prerequisites/prerequisites.md
Labels: documentation

#571 fix(tutorials): update consume data flow
  docs/tutorials/e2e/boost/consumeData.md
Labels: documentation

#658 doc(open meetings): add four open meetings
  community/open-meetings.mdx
  static/meetings/committer-office-hour.ics
  static/meetings/newjoiner-office-hour.ics
  static/meetings/office-hour.ics
  static/meetings/security-office-hour.ics
Labels: documentation

#682 doc(open meetings): change of the committer meeting rotation
  community/open-meetings.mdx
  static/meetings/committer-office-hour.ics
Labels: documentation

#674 feat: enable markdown linter for kits
  .github/workflows/lint-on-pull-request.yaml
  README.md
  package.json
Labels: enhancement

#687 doc(blog): add news blog entry for second community days
  blog/2024-05-16-community-days.mdx
  static/img/Tractus-X_Community_Days_24-05.png
  utils/newsTitles.js
Labels: documentation

#679 doc(open meetings): add new open meeting for edc weekly
  community/open-meetings.mdx
  static/meetings/edc-weekly-extended.ics
Labels: documentation

#704 Fix Knowledge Agents Kit: Linter and Version References Upped to 24.03
  docs-kits/kits/knowledge-agents/adoption-view/intro.md
  docs-kits/kits/knowledge-agents/development-view/Arc42.md
  docs-kits/kits/knowledge-agents/development-view/modules.md
  docs-kits/kits/knowledge-agents/development-view/reference.md
  docs-kits/kits/knowledge-agents/operation-view/agent_edc.md
  docs-kits/kits/knowledge-agents/operation-view/deployment.md
  docs-kits/kits/knowledge-agents/operation-view/policy.md
  docs-kits/kits/knowledge-agents/operation-view/provider.md
  docs-kits/kits/knowledge-agents/operation-view/testbed.md
  docs-kits/kits/knowledge-agents/page_changelog.md
  openApi/agents/agent-openapi.yaml
Labels: bug

#706 feat(open meetings): add functionality to add additional links
  community/open-meetings.mdx
  src/components/OpenMeetings/MeetingInfo.jsx
Labels: documentation, enhancement

#711 doc(open meetings): add new open meeting for osp feature demo
  community/open-meetings.mdx
  static/meetings/osp-feature-demo.ics
Labels: documentation

#716 chore(meetings): add matrix chats as additional information
  community/open-meetings.mdx
Labels: documentation

#715 doc(blog): Adapt detailed planning information
  blog/2024-05-16-community-days.mdx
Labels: documentation
