Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2024-12, with the labels that each got.

#1095 docs: update TRG 7-04 to unbind DEPENDENCIES file from the main branch
  docs/release/trg-7/trg-7-01.md
  docs/release/trg-7/trg-7-04.md
Labels: documentation

#1102 doc(open-meeting): adjusted open meeting for bpdm
  community/open-meetings.mdx
Labels: documentation

#1064 [Traceability KIT 24.12] Special Characteristics
  docs-kits/kits/Industry Core Kit/Software Development View/part_aspect-model-overview.mdx
  docs-kits/kits/Industry Core Kit/page_changelog.mdx
  docs-kits/kits/Traceability Kit/Software Development View/part_aspect-models.mdx
  docs-kits/kits/Traceability Kit/page_business_view.mdx
  docs-kits/kits/Traceability Kit/page_changelog.mdx
Labels: enhancement

#1028 [Traceability KIT 24.12] Block Notification
  docs-kits/kits/Traceability Kit/Software Development View/page_app-provider_software-development-view.mdx
  docs-kits/kits/Traceability Kit/assets/architecture_level_1.png
  docs-kits/kits/Traceability Kit/assets/architecture_level_1.svg
  docs-kits/kits/Traceability Kit/assets/architecture_level_1.svg.license
  docs-kits/kits/Traceability Kit/assets/block-notification-state-model-interaction.svg
  docs-kits/kits/Traceability Kit/assets/block-notification-state-model-interaction.svg.license
  docs-kits/kits/Traceability Kit/assets/block-notification-state-model.svg
  docs-kits/kits/Traceability Kit/assets/block-notification-state-model.svg.license
  docs-kits/kits/Traceability Kit/assets/block_notifications.svg
  docs-kits/kits/Traceability Kit/assets/block_notifications.svg.license
  docs-kits/kits/Traceability Kit/assets/quality_notifications.svg
  docs-kits/kits/Traceability Kit/diagrams/block-notification-send-receive.svg
  docs-kits/kits/Traceability Kit/diagrams/block-notification-send-receive.svg.license
  docs-kits/kits/Traceability Kit/diagrams/block-notification-update-status.svg
  docs-kits/kits/Traceability Kit/diagrams/block-notification-update-status.svg.license
  docs-kits/kits/Traceability Kit/openapi/block-notifications-1-0-0.yaml
  docs-kits/kits/Traceability Kit/page_architecture-view.mdx
  docs-kits/kits/Traceability Kit/page_business_view.mdx
  docs-kits/kits/Traceability Kit/page_changelog.mdx
Labels: enhancement

#1105 docs(open-meetings): change CEST/CET where needed
  community/open-meetings.mdx
Labels: documentation

#1114 docs(release-planning): add needed information for release planning 25.06
  blog/2025-02-19-release-planning-R25.06.mdx
  community/open-meetings.mdx
  utils/newsTitles.js
Labels: documentation

#1116 docs(open meetings): delete redundante content
  blog/2025-02-19-release-planning-R25.06.mdx
Labels: documentation

#1118 docs(news blog): add community days recap
  blog/2024-12-16-community-days-recap.mdx
  static/img/tractus-x-community-days-24-12-group.png
  static/img/tractus-x-community-days-24-12-group.png.license
  utils/newsTitles.js
Labels: documentation

#968 chore(products/repositories): adapt/update whole list of products/repositories
  utils/products.js
Labels: documentation, enhancement

#1112 docs(open-meetings): update office hour and extend meetings for 2025
  community/open-meetings.mdx
Labels: documentation
