Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2024-03, with the labels that each got.

#725 feat(open meetings): add anchor to link to open meeting
  src/components/OpenMeetings/MeetingInfo.jsx
Labels: enhancement

#730 [Connector Kit] Incorporate Review Comments for R24-03
  docs-kits/kits/Connector Kit/Adoption View/adoption-view.md
  docs-kits/kits/Connector Kit/assets/domain-model.png
  docs-kits/kits/Connector Kit/assets/edc_architecture.png
  docs-kits/kits/Connector Kit/page_changelog.md
Labels: documentation

#709 doc(ESS Kit): Inital commit
  docs-kits/kits/ESS-Kit/page_adoption-view.md
  docs-kits/kits/ESS-Kit/page_documentation.md
  sidebarsDocsKits.js
  static/kits/ESS-Kit/CatenaX_ESS_KitBlockDiagram.png
  static/kits/ESS-Kit/CatenaX_ESS_KitBusinessArchitecture.png
  static/kits/ESS-Kit/CatenaX_ESS_KitCustomerJourney.png
  static/kits/ESS-Kit/CatenaX_ESS_KitSequenceView.drawio.svg
  static/kits/ESS-Kit/CatenaX_ESS_KitSequenceView.png
  static/kits/ESS-Kit/CatenaX_ESS_KitSequenceView.svg
  static/kits/ESS-Kit/ESSKit.png
  static/kits/ESS-Kit/ess-kit-icon.png
  utils/kitsGallery.js
Labels: documentation

#734 doc(ess-kit): add changelog to kit
  docs-kits/kits/ESS-Kit/changelog.md
  docs-kits/kits/ESS-Kit/page_adoption-view.md
  docs-kits/kits/ESS-Kit/page_documentation.md
Labels: documentation

#630 docs(kit): updated ecopasskit adoption view, dpp aspect added, business arch updated and other document changes
  docs-kits/kits/Eco_Pass_KIT/changelog.md
  docs-kits/kits/Eco_Pass_KIT/page-adoption-view.md
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BatteryPass_a_example.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BatteryPass_a_example.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BatteryPass_a_example.svg
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BatteryPass_a_example.svg.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BusinessValue.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BusinessValue.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BusinessValue.svg
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-BusinessValue.svg.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.svg
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.svg.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.png
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.png.license
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.svg
  docs-kits/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.svg.license
Labels: documentation, website

#731 doc(tutorials): add some information related to used backend
  docs/tutorials/e2e/boost/consumeData.md
  docs/tutorials/e2e/connect/deployComponents.md
  static/tutorials/e2e/consume_data_backend.png
Labels: documentation

#781 fix(open meetings): cleanup open meetings
  DEPENDENCIES
  community/open-meetings.mdx
Labels: documentation
