Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2024-01, with the labels that each got.

#587 doc(open meetings): add new open planning meeting
  community/open-meetings.mdx
Labels: documentation

#616 feat(community): adapt open meeting infos
  community/open-meetings.mdx
  src/components/OpenMeetings/MeetingInfo.jsx
  static/meetings/alignment-and-planning-trace-x.ics
Labels: documentation, enhancement

#570 fix(tutorials): Update API health check commands and add JSON parsing with jq
  docs/tutorials/e2e/boost/provideData.md
  docs/tutorials/e2e/connect/deployComponents.md
Labels: documentation

#623 fix(tutorials): issues provided as feedback at the community days
  docs/tutorials/e2e.md
  sidebars.js
Labels: bug, documentation

#624 fix: reference links for helm test TRG 5-09 within TRG 5-08
  docs/release/trg-5/trg-5-08.md
  docs/release/trg-5/trg-5-09.md
Labels: bug

#641 doc(open meetings): add new open meeting for trace-x
  community/open-meetings.mdx
  static/meetings/coordination-feature-development-trace-x.ics
Labels: documentation

#642 fix(connector kit): fix markdown linter errors for connector kit
  docs-kits_versioned_docs/version-23.09/kits/tractusx-edc/docs/README.md
  docs-kits_versioned_docs/version-23.09/kits/tractusx-edc/docs/kit/operation-view/page08_api.md
  docs-kits_versioned_docs/version-23.09/kits/tractusx-edc/docs/samples/Transfer Data.md
  docs-kits_versioned_docs/version-23.12/kits/tractusx-edc/docs/README.md
  docs-kits_versioned_docs/version-23.12/kits/tractusx-edc/docs/kit/operation-view/page08_api.md
  docs-kits_versioned_docs/version-23.12/kits/tractusx-edc/docs/samples/Transfer Data.md
  docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/docs/kit/operation-view/page08_api.md
  docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/docs/samples/Local TXDC Setup.md
  docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/docs/samples/Transfer Data.md
  docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/edc-tests/cucumber/README.md
Labels: bug, documentation
