Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2025-07, with the labels that each got.

#1289 docs(release-planning): add release planning 25.12
  blog/2025-07-01-release-planning-R25.12.md
  community/open-meetings.mdx
  static/img/release-planning-R25.12.png
  utils/newsTitles.js
Labels: documentation

#1295 fix(naming consistency): rename DevHub -> Developer Hub
  utils/carouselCommunityInfo.js
Labels: website

#1304 chore(trg-change-log): delete TRG change log
  docs/release/trg-0/trg-0.md
Labels: documentation, TRG
