Repository eclipse-tractusx/eclipse-tractusx.github.io, pull requests merged in 2025-05, with the labels that each got.

#1256 Added SCSS and two buttons with KITs and our Open Source code in Title
  DEPENDENCIES
  docs-kits/kits/behaviour-twin-kit/adoption-view/terminology.md
  docs-kits_versioned_docs/version-24.08/kits/behaviour-twin-kit/adoption-view/terminology.md
  docs-kits_versioned_docs/version-24.12/kits/behaviour-twin-kit/adoption-view/terminology.md
  docs-kits_versioned_docs/version-25.03/kits/behaviour-twin-kit/adoption-view/terminology.md
  docs/release/trg-0/trg-9-01.md
  documentation/kit-artifacts.md
  documentation/kit-getting-started.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/HomePageHeader/index.js
  src/components/HomePageHeader/styles.module.css
  src/css/custom.css
  src/scss/components/HomePageHeader.module.scss
  src/scss/config/_mixins.scss
  src/scss/config/_variables.scss
  src/scss/main.scss
  utils/carouselKitdeepdive.js
Labels: enhancement, KIT

#1261 docs(open planning): add detailed agenda
  blog/2025-03-20-release-planning-R25.09.mdx
Labels: documentation

#1265 feat(dash-action): adapt to be executed only on change
  .github/workflows/dash.yaml
Labels: enhancement, website

#1262 docs(product-list): cleanup product list
  utils/products.js
Labels: documentation
